import type { Metadata } from "next";
import React from "react";
import { Inter } from "next/font/google";
import Sidebar from "@/components/sidebar";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

const RootLayout: React.FC<RootLayoutProps> = ({
  children,
}: {
  children: React.ReactNode;
}) => (
  <html lang="en">
    <body className={inter.className}>
      <div className="flex p-10 gap-10 h-full">
        <Sidebar />
        {children}
      </div>
    </body>
  </html>
);

export default RootLayout;
